# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('white_player', models.CharField(max_length=100)),
                ('black_player', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('move_type', models.PositiveSmallIntegerField(default=1)),
                ('src', models.PositiveSmallIntegerField()),
                ('dest', models.PositiveSmallIntegerField()),
                ('e_p_field', models.PositiveSmallIntegerField(null=True)),
                ('captured_piece', models.PositiveSmallIntegerField(default=0)),
                ('prom_piece', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kate.Match')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kate.Match'),
        ),
    ]
