# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bKg_first_movecnt',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bKg_x',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bKg_y',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bRk_a8_first_movecnt',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bRk_h8_first_movecnt',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fifty_moves_count',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wKg_first_movecnt',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wKg_x',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wKg_y',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wRk_a1_first_movecnt',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wRk_h1_first_movecnt',
        ),
    ]
