# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0002_auto_20180311_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='black_player',
            new_name='black_player_name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='white_player',
            new_name='white_player_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='count',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
    ]
