

TACTICS = {
    'defend-check' : 0,
    'defend-king-attack-urgent' : 1,
    'defend-king-attack' : 2,
    'promotion' : 3,
    'tactical-draw' : 4,
    'capture-good-deal' : 5,
    'running-pawn-in-endgame' : 6, 
    'attack-king-good-deal' : 7,
    'does-unpin' : 8, 
    'attack-stormy' : 9,
    'flee-urgent' : 10,
    'support-good-deal' : 11,
    'block' : 12,
    'discl-support-good-deal' : 13,
    'defend-fork' : 14,
    'attack-good-deal' : 15,
    'discl-attack-good-deal' : 16,
    'controles-file-good-deal' : 17,
    'castling' : 18,
    'capture-bad-deal' : 19,
    'attack-king-bad-deal' : 20,
    'defend-fork-downgraded' : 21,
    'flee-downgraded' : 22,
    'support-downgraded' : 23,
    'attack-downgraded' : 24,
    'support-unattacked' : 25,
    'progress' : 26, 
    'flee' : 27,
    'attack-bad-deal' : 28,
    'support-bad-deal' : 29,
    'undefined' : 30 }


PRIO = {
    'prio1' : 0,
    'prio2' : 1,
    'prio3' : 2,
    'prio4' : 3,
    'prio5' : 4,
    'prio6' : 5,
    'prio7' : 6,
    'prio8' : 7,
    'prio9' : 8,
    'prio10' : 9 }


TACTICS_TO_PRIO = {
      TACTICS['defend-check'] : PRIO['prio1'],
      TACTICS['defend-king-attack-urgent'] : PRIO['prio2'],
      TACTICS['defend-king-attack'] : PRIO['prio2'],
      TACTICS['promotion'] : PRIO['prio2'],
      TACTICS['tactical-draw'] : PRIO['prio2'],
      TACTICS['capture-good-deal'] : PRIO['prio2'],
      TACTICS['running-pawn-in-endgame'] : PRIO['prio2'], 
      TACTICS['attack-king-good-deal'] : PRIO['prio2'],
      TACTICS['does-unpin'] : PRIO['prio2'], 
      TACTICS['attack-stormy'] : PRIO['prio3'],
      TACTICS['flee-urgent'] : PRIO['prio3'], 
      TACTICS['support-good-deal'] : PRIO['prio4'], 
      TACTICS['block'] : PRIO['prio4'], 
      TACTICS['discl-support-good-deal'] : PRIO['prio4'], 
      TACTICS['defend-fork'] : PRIO['prio4'], 
      TACTICS['attack-good-deal'] : PRIO['prio4'], 
      TACTICS['discl-attack-good-deal'] : PRIO['prio4'], 
      TACTICS['controles-file-good-deal'] : PRIO['prio5'], 
      TACTICS['castling'] : PRIO['prio5'],
      TACTICS['capture-bad-deal'] : PRIO['prio6'], 
      TACTICS['attack-king-bad-deal'] : PRIO['prio6'], 
      TACTICS['defend-fork-downgraded'] : PRIO['prio7'], 
      TACTICS['flee-downgraded'] : PRIO['prio7'], 
      TACTICS['support-downgraded'] : PRIO['prio7'], 
      TACTICS['attack-downgraded'] : PRIO['prio7'],
      TACTICS['support-unattacked'] : PRIO['prio8'], 
      TACTICS['progress'] : PRIO['prio8'], 
      TACTICS['flee'] : PRIO['prio8'],
      TACTICS['attack-bad-deal'] : PRIO['prio9'], 
      TACTICS['support-bad-deal'] : PRIO['prio9'],
      TACTICS['undefined'] : PRIO['prio10'] }

